# Generated by Django 4.1.2 on 2022-11-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0002_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feelings.feeling'),
        ),
    ]
