# Generated by Django 4.1.2 on 2022-11-23 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0003_alter_log_feeling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
    ]
